src/voucher/voucher/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from voucherapp import views

urlpatterns = [
    url(r'^',  include(admin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url('^accounts/', admin.site.urls),
    url(r'^voucherapp/', include('voucherapp.urls', namespace='voucherapp')),
    #url(r'^', include('voucherapp.urls', namespace='voucherapp')),
]

src/voucher/voucherapp/urls.py
from django.conf.urls import url, include

from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    url(r'^logfile/$', views.logfile, name='logfile'),
    url(r'^simulate/$', views.simulate, name='simulate'),
    url(r'^upload/$', views.upload, name='upload'),
]

src/voucher/voucherapp/models.py
# -*- coding: utf-8 -*-

from django.db import models

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

# Create your models here.

class NullableCharField(models.CharField):
    description = "CharField that stores NULL but returns ''"
    #__metaclass__ = models.SubfieldBase
    #def from_db_value(self, value, expression, connection, context):
    #    return models.CharField.from_db_value(self, value, expression, connection, context)
    def to_python(self, value):
        if isinstance(value, models.CharField):
            return value
        return value or ''
    def get_prep_value(self, value):
        return value or None
        

class Person(models.Model):
    #rfid = models.CharField(unique=True, max_length=16, verbose_name='RFID', help_text='')
    rfid = NullableCharField(blank=True, null=True, default=None, unique=True, max_length=16, verbose_name='RFID', help_text='')
    personal_number = models.CharField(unique=True, null=False, blank=False, max_length=16, verbose_name='Osobní číslo', help_text='') 
    center = models.IntegerField(default=0, verbose_name='Středisko', help_text='')
    
    first_name = models.CharField(null=False, blank=True, max_length=64, verbose_name='Křestní jméno')
    last_name = models.CharField(null=False, blank=True, max_length=64, verbose_name='Příjmení')
    note = models.CharField(null=False, blank=True, max_length=256, verbose_name='Poznámka')
    
    quantity = models.IntegerField(default=0, verbose_name='počet kupónů na měsíc', help_text='')
    released = models.IntegerField(default=0, verbose_name='počet vydaných kupónů za měsíc', help_text='')
    last_released = models.DateTimeField(null=True, blank=True, verbose_name='datum a čas vydání', help_text='')
     
    def __str__(self):
        return str(self.personal_number) #+ ' ' + self.last_name + ' ' + self.first_name
        
    class Meta:
        verbose_name = 'Osoba'
        verbose_name_plural = '  Osoby'

class Voucher(models.Model):
    person = models.ForeignKey(Person, related_name='voucher_user', verbose_name='Osoba')
    datetime = models.DateTimeField(verbose_name='datum a čas vydání', help_text='')
    
    def __str__(self):
        return str(self.person) + ': ' + str(self.datetime)
        
    class Meta:
        verbose_name = 'Poukaz'
        verbose_name_plural = 'Poukazy'
        ordering = ('person',)

src/voucher/voucherapp/forms.py
from django import forms
from .models import Person

class RFIDForm(forms.Form):
    
    person = forms.ModelChoiceField(required=False , queryset=Person.objects.all(), empty_label='', to_field_name='rfid', label='Osoba')
    printout = forms.BooleanField(required=False ,initial=False, label='Tisk')

src/voucher/voucherapp/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render

# Create your views here.

import os
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from .forms import RFIDForm

from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage

import management.commands.core

class StrLogger:
    log = []
    def error(self, msg):
        self.log.append('ERROR: ' + msg)
    def warning(self, msg):
        self.log.append('WARNING: ' + msg)
    def info(self, msg):
        pass
        #self.log.append('INFO: ' + msg)
 
@login_required(login_url='/accounts/login/')      
def upload(request):
    
    if request.method == 'POST':
        filepath = request.FILES.get('filepath', False) 
        if filepath:
            fs = FileSystemStorage()
            filename = fs.save(filepath.name, filepath)
            uploaded_file_url = fs.url(filename)
                
            strLogger = StrLogger()
            strLogger.log = []
                    
            management.commands.core.importFile(uploaded_file_url, strLogger)

            fs.delete(filename)
                
            return render(request, 'voucherapp/upload.html', {
                'uploaded_file_url': uploaded_file_url,
                'error_messages': strLogger.log,
            })
    
    return render(request, 'voucherapp/upload.html')
     
@login_required(login_url='/accounts/login/')
def simulate(request, rfid = 0):
   
    if request.method == 'POST': # and 'submit' in request.POST:
        form = RFIDForm(request.POST)
    else:
        form  = RFIDForm()
    
    if not form.is_valid():
        rfid = 0
        pritout = False
    else:
        person = form.cleaned_data['person']
        printout = form.cleaned_data['printout']
        if person == None:
            rfid = 0
        else:
            rfid = person.rfid
   
    result = management.commands.core.getPreparedPerson(rfid)
 
    if rfid <> 0:
        if result[0]:
            if management.commands.core.printResult(result, printout):
                management.commands.core.saveVoucher(result[1])
            else:
                result = (False, result[1], 'Chyba tiskárny!')
    else:
        result = (False, result[1], 'Neznámé ID!')
            
    context = {
        'result': result[0],
        'person': result[1],
        'form' : form,
        'message' : result[2],
    }
            
    return render(request, 'voucherapp/simulate.html', context)
 
@login_required(login_url='/accounts/login/')
def logfile(request):
    filename = 'logfile'
    SITE_ROOT = os.path.abspath(os.path.dirname(__name__))
    
    filefullpath = os.path.join(SITE_ROOT, filename)

    try:  
        import tempfile
        with open(tempfile.mktemp(), 'w') as tf:
            try:
                with open(filefullpath + '.1') as flog:
                    tf.write(flog.read())
            except:
                pass
            with open(filefullpath) as flog:
                tf.write(flog.read())
      
        wrapper = FileWrapper(open(tf.name, 'rb'))
       
        response = HttpResponse(wrapper, content_type='text/plain; charset=utf-8')
        response['Content-Disposition'] = 'inline; filename={0}'.format(filename + '.txt')
        response['Content-Length'] = os.path.getsize(tf.name)
        
        os.remove(tf.name)
        return response

    except Exception as e:
        response = 'Log neni dostupny!<br>Zkontrolujete logfile<br>tail -f logfile<br>Chyba: {0} {1}'.format(str(e), filefullpath)
        return HttpResponse(response)

src/voucher/voucherapp/templates/voucherapp/base.html
{% load staticfiles %}

<html>
<head>
</head>

<body>
<p>
<a href="{% url 'admin:index' %}">Správce</a> / 
<a href="{% url 'voucherapp:logfile' %}">Log</a> /    
<a href="{% url 'voucherapp:simulate' %}">Simulace</a> / 
<a href="{% url 'voucherapp:upload' %}">Import</a>   
</p>
<hr>
<p>
{% block content %}

{% endblock %}
</p>
</body>
</html>

src/voucher/voucherapp/templates/voucherapp/simulate.html
{% extends 'voucherapp/base.html' %}

{% load staticfiles %}

{% block content %}

<h1>SIMULACE</h1>

    <form method="POST" action=".">
        {% csrf_token %}
Osoba: 
        {{ form.person }}
Tisk na tiskárně:
        {{ form.printout }}
            <button type="submit" name="submit"> Odeslat </button>
  
    </form>


<hr>

{% if result %}
    <h2>VYDÁNO</h2>
{% else %}
    {% if person %}
        <h2>NEVYDÁNO: {{ message }} </h2>
    {% else %}
        <h2>NEVYDÁNO: {{ message }} </h2>
    {% endif %}
{% endif %}

{% if person %}
    <h3> {{ person }} </h3>
    <table>
    <tr><td>RFID: </td><td>{{ person.rfid }} </td></tr>
    <tr><td>Jméno: </td><td> {{ person.first_name }} {{ person.last_name }}</td></tr>
    <tr><td>Osobní číslo: </td><td> {{ person.personal_number }} </td></tr>
    <tr><td>Středisko: </td><td> {{ person.center }} </td></tr>
    <tr><td>Počet kupónů na měsíc: </td><td> {{ person.quantity }} </td></tr>
    <tr><td>Počet vydaných kupónů za měsíc: </td><td> {{ person.released }} </td></tr>   
    <tr><td>Datum a čas vydání: </td><td>{{ person.last_released }} </td></tr>   
    </table>
    
{% endif %}

<hr>
{% if result %}
<h2>TISK</h2>

{% comment %}
    <table>
    <tr><td>Osobní číslo: </td><td> {{ person.personal_number }} </td></tr>
    <tr><td>Středisko: </td><td> {{ person.center }} </td></tr>
    <tr><td>Vydáno: </td><td> {{ person.released }} z {{ person.quantity }} </td></tr>
    <tr><td>Měsíc: </td><td> {{ person.last_released|date:"F" }} {{ person.last_released|date:"Y" }} </td></tr>
    </table>
{% else %}
    {{ message }}
{% endcomment %}

{% endif %}

{% endblock %} 

src/voucher/voucherapp/templates/voucherapp/upload.html
{% extends 'voucherapp/base.html' %}

{% load staticfiles %}

{% block content %}

<h1>IMPORT</h1>

{% comment %}
https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
{% endcomment %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="filepath">
    <button type="submit"> Importovat </button>
</form>

<hr>

{% if uploaded_file_url %}
{% if error_messages|length > 0 %}
    <h2>CHYBA</h2>
{% else %}
    <h2>OK</h2>
{% endif %}


<p>Soubor: {{ uploaded_file_url }}</p>


{% if error_messages %}
{%for msg in error_messages%}
    {{ msg }} <br>
{% endfor %}
{% endif %}
{% endif %}
{% endblock %} 